update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -27,12 +27,9 @@ jobs:
           fallback: 0.0.0
       - name: Check new tag
         if: ${{ env.TAG }} == ${{ steps.last_tag.outputs.tag }}
-        steps:
-          - name: A/B Check
-            if: ${{ envA }} != ${{ envB }}
-            run: |
-              echo "::error::Tag ${{ env.TAG }} already exists!"
-              exit 1
+        run: |
+          echo "::error::Tag ${{ env.TAG }} already exists!"
+          exit 1
       - name: Set JAR_NAME_TEMPLATE
         run: |
           echo "JAR_NAME=${{ env.JAR_NAME_TEMPLATE }}" | sed "s/*/${{ github.event.inputs.version }}/g" >> $GITHUB_ENV
