update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -17,8 +17,47 @@ env:
   TELEGRAM_UPDATE_PHOTO_CMD: telegram_update_photo.sh
 
 jobs:
+  check-input:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions-ecosystem/action-regex-match@v2
+        id: regex-match
+        with:
+          text: ${{ github.event.inputs.version }}
+          regex: '^\d+\.\d+\.\d+$'
+      - name: Check release version
+        if: steps.regex-match.outputs.match == ''
+        run: |
+          echo "::error::Incorrect release version format: ${{ github.event.inputs.version }}. Expected format: x.y.z!"
+          exit 1
+  check-tag:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Get latest tag
+        id: get_latest_tag
+        uses: actions-ecosystem/action-get-latest-tag@v1
+      - name: Print tags
+        run: |
+          echo "Existing tag: ${{ steps.get_latest_tag.outputs.tag }}"
+          echo "New tag: ${{ env.TAG }}"
+      - name: Check new tag
+        if: env.TAG == steps.get_latest_tag.outputs.tag
+        run: |
+          echo "::error::Tag ${{ env.TAG }} already exists!"
+          exit 1
+  create-tag:
+    runs-on: ubuntu-latest
+    needs: [check-input, check-tag]
+    steps:
+      - name: Create Tag
+        uses: rickstaa/action-create-tag@v1
+        with:
+          tag: ${{ env.TAG }}
   setenv:
     runs-on: ubuntu-latest
+    needs: [check-input, check-tag]
     steps:
       - name: Set JAR_NAME_TEMPLATE
         run: |
@@ -34,32 +73,42 @@ jobs:
           echo "TAG=${{ env.TAG }}"
   release:
     runs-on: ubuntu-latest
-    needs: [setenv]
+    needs: [create-tag, setenv]
     steps:
-      - uses: actions-ecosystem/action-regex-match@v2
-        id: regex-match
-        with:
-          text: ${{ github.event.inputs.version }}
-          regex: '^\d+\.\d+\.\d+$'
-      - name: Check release version
-        if: steps.regex-match.outputs.match == ''
-        run: |
-          echo "::error::Incorrect release version format: ${{ github.event.inputs.version }}. Expected format: x.y.z!"
-          exit 1
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Get latest tag
-        id: get_latest_tag
-        uses: actions-ecosystem/action-get-latest-tag@v1
-      - name: Print tags
-        run: |
-          echo "Existing tag: ${{ steps.get_latest_tag.outputs.tag }}"
-          echo "New tag: ${{ env.TAG }}"
-      - name: Check new tag
-        if: env.TAG == steps.get_latest_tag.outputs.tag
-        run: |
-          echo "::error::Tag ${{ env.TAG }} already exists!"
-          exit 1
+      - name: Set up JDK 8
+        uses: actions/setup-java@v3
+        with:
+          java-version: '8'
+          distribution: 'adopt'
+          cache: maven
+      - name: Build with Maven
+        run: mvn package
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ env.TAG }}
+          release_name: ${{ env.TAG }}
+          draft: true
+      - name: Upload Release Asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ env.JAR_PATH }}
+          asset_name: ${{ env.JAR_NAME }}
+          asset_content_type: application/java-archive
+  remote-upload:
+    runs-on: ubuntu-latest
+    needs: [create-tag, setenv]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
       - name: Set up JDK 8
         uses: actions/setup-java@v3
         with:
@@ -90,25 +139,3 @@ jobs:
             echo "java -jar ${{ env.JAR_NAME }} telegram.login" >> ${{ env.TELEGRAM_LOGIN_CMD }}
             echo "java -jar ${{ env.JAR_NAME }} telegram.logout" >> ${{ env.TELEGRAM_LOGOUT_CMD }}
             echo -e "cd ${{ env.REMOTE_DIR }}\njava -jar ${{ env.JAR_NAME }} telegram.update_photo" >> ${{ env.TELEGRAM_UPDATE_PHOTO_CMD }}
-      - name: Create Tag
-        uses: rickstaa/action-create-tag@v1
-        with:
-          tag: ${{ env.TAG }}
-      - name: Create Release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ env.TAG }}
-          release_name: ${{ env.TAG }}
-          draft: true
-      - name: Upload Release Asset
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ${{ env.JAR_PATH }}
-          asset_name: ${{ env.JAR_NAME }}
-          asset_content_type: application/java-archive
