update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -17,29 +17,8 @@ env:
   TELEGRAM_UPDATE_PHOTO_CMD: telegram_update_photo.sh
 
 jobs:
-  validate:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Get latest tag
-        id: get_latest_tag
-        uses: actions-ecosystem/action-get-latest-tag@v1
-#        with:
-#          with_initial_version: true
-#          initial_version: v2.0.0
-      - name: Print tags
-        run: |
-          echo "Existing tag: ${{ steps.get_latest_tag.outputs.tag }}"
-          echo "New tag: ${{ env.TAG }}"
-      - name: Check new tag
-        if: env.TAG == steps.get_latest_tag.outputs.tag
-        run: |
-          echo "::error::Tag ${{ env.TAG }} already exists!"
-          exit 1
   setenv:
     runs-on: ubuntu-latest
-    needs: [validate]
     steps:
       - name: Set JAR_NAME_TEMPLATE
         run: |
@@ -57,6 +36,30 @@ jobs:
     runs-on: ubuntu-latest
     needs: [setenv]
     steps:
+      - uses: actions-ecosystem/action-regex-match@v2
+        id: regex-match
+        with:
+          text: ${{ github.event.inputs.version }}
+          regex: '^\d+\.\d+\.\d+$'
+      - name: Check release version
+        if: steps.regex-match.outputs.match == ''
+        run: |
+          echo "::error::Incorrect release version format: ${{ github.event.inputs.version }}. Expected format: x.y.z!"
+          exit 1
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Get latest tag
+        id: get_latest_tag
+        uses: actions-ecosystem/action-get-latest-tag@v1
+      - name: Print tags
+        run: |
+          echo "Existing tag: ${{ steps.get_latest_tag.outputs.tag }}"
+          echo "New tag: ${{ env.TAG }}"
+      - name: Check new tag
+        if: env.TAG == steps.get_latest_tag.outputs.tag
+        run: |
+          echo "::error::Tag ${{ env.TAG }} already exists!"
+          exit 1
       - name: Set up JDK 8
         uses: actions/setup-java@v3
         with:
